# Generated by Django 5.1.1 on 2024-09-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_station', models.CharField(max_length=255)),
                ('end_station', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='route_images/')),
            ],
        ),
    ]
