# Generated by Django 5.1.1 on 2024-10-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('departure', models.CharField(choices=[('Yaoundé', 'Yaoundé'), ('Bafoussam', 'Bafoussam'), ('Ngaoundéré', 'Ngaoundéré'), ('Douala', 'Douala'), ('Bamenda', 'Bamenda'), ('Garoua', 'Garoua')], max_length=255)),
                ('arrival', models.CharField(choices=[('Yaoundé', 'Yaoundé'), ('Bafoussam', 'Bafoussam'), ('Ngaoundéré', 'Ngaoundéré'), ('Douala', 'Douala'), ('Bamenda', 'Bamenda'), ('Garoua', 'Garoua')], max_length=255)),
                ('classification', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('VIP', 'VIP')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('railway_name', models.CharField(default='Default Railway', max_length=255)),
            ],
        ),
    ]
