# Generated by Django 5.1.1 on 2024-10-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='railway_name',
            field=models.CharField(default='E-railway Railway', max_length=255),
        ),
    ]
