# Generated by Django 5.1.1 on 2024-10-01 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_ticket_railway_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('periodic', 'Periodic'), ('monthly', 'Monthly')], max_length=10)),
                ('status', models.CharField(choices=[('not_done', 'Not Done'), ('done', 'Done')], default='not_done', max_length=10)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('sanction_applied', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'maintenance'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
