# Generated by Django 5.1.1 on 2024-10-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_damagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Untitled Ticket', max_length=100),
        ),
    ]
